// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCElQQwRopPtj4Ss-OFL-qHIE3B_RR9U4',
    appId: '1:848632634547:web:0f0cc6b5b262ae667fe4c6',
    messagingSenderId: '848632634547',
    projectId: 'lancaster-mode',
    authDomain: 'lancaster-mode.firebaseapp.com',
    storageBucket: 'lancaster-mode.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCRNwGedBBEjRM7Bfgt7N7dCWf6Bxy1g',
    appId: '1:848632634547:android:5f9de9e7c18b932b7fe4c6',
    messagingSenderId: '848632634547',
    projectId: 'lancaster-mode',
    storageBucket: 'lancaster-mode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqrEzsUsjMJnIhXi-YKtq_6BhJqOQcA90',
    appId: '1:848632634547:ios:75be64fe054f60fb7fe4c6',
    messagingSenderId: '848632634547',
    projectId: 'lancaster-mode',
    storageBucket: 'lancaster-mode.firebasestorage.app',
    iosBundleId: 'com.example.lancasterMode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqrEzsUsjMJnIhXi-YKtq_6BhJqOQcA90',
    appId: '1:848632634547:ios:75be64fe054f60fb7fe4c6',
    messagingSenderId: '848632634547',
    projectId: 'lancaster-mode',
    storageBucket: 'lancaster-mode.firebasestorage.app',
    iosBundleId: 'com.example.lancasterMode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCElQQwRopPtj4Ss-OFL-qHIE3B_RR9U4',
    appId: '1:848632634547:web:e992da067af8c1347fe4c6',
    messagingSenderId: '848632634547',
    projectId: 'lancaster-mode',
    authDomain: 'lancaster-mode.firebaseapp.com',
    storageBucket: 'lancaster-mode.firebasestorage.app',
  );
}
